---
title: "Abundance of large T. bidentata"
output: html_document
date: "2025-05-26"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r clear environment}
# clear environment for maximum reproducibility
rm(list=ls())
```

```{r load packages}
# load librarian (package for installing/loading packages)
if (!require("librarian")) install.packages("librarian")

# load requried packages
librarian::shelf(here, # relative file paths 
                 tidyverse, # data wrangling
                 BlakeRMills/MoMAColors, # color palette
                 patchwork, # for putting figures together
                 glmmTMB, # for models
                 DHARMa, # for residuals
                 performance, # also for residuals
                 car # for type II ANOVAs
                 )
```

```{r explicitly assign functions if needed}
# make sure correct functions attached to the correct packages
summarize <- dplyr::summarize
group_by <- dplyr::group_by
select <- dplyr::select
```

```{r set seed}
set.seed(0429)
```

# Set the color palette and graphics

```{r consistent color palette by treatment}
colorz <- moma.colors("Warhol", n=15, type="discrete")
b.color <- colorz[3]
control.color <- colorz[9]
crab.color <- colorz[1]
n.color <- colorz[6]
```

```{r set graphing theme}
# ggplot theme
theme_set(
  theme_bw(base_size = 20) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
    theme(text = element_text(size=20)) +
    theme(plot.title = element_text(vjust = -6))
) 
```

# Read in data

```{r load data}
# metadata (treatments, block, coral volume, etc.) -- includes retention data
metadata <- read_csv(here("data", "metadata.csv")) %>% 
  # exclude coral that experienced 100% tissue loss
  filter(coral_id != 25)
```

# Plot

Plot number of large T. bidentata after one month

```{r plot summer 2021}
metadata %>% 
  # get column names/values nice for plotting
  mutate(Nutrients = case_when(nutrients == "Y" ~ "Enriched",
                               nutrients == "N" ~ "Ambient")) %>% 
  mutate(Crab = case_when(crab == "Y" ~ "Crab",
                               crab == "N" ~ "No crab")) %>% 
  # only looking at corals in the crab treatment
  filter(Crab == "Crab") %>% 
  ggplot(aes(x = Nutrients, y = tbiden_1_month, fill = Nutrients)) +
  geom_boxplot(size = 1,
               outlier.shape = NA) +
  geom_point(size = 2.2,
             color = "black",
             alpha = 0.65,
             position = position_jitterdodge(jitter.width = 0.2,
                                             jitter.height = 0,
                                             dodge.width = 0.75)) +
  scale_fill_manual(values = c("Enriched" = n.color,
                               "Ambient" = b.color)) +
  ylab(expression(paste("Large ", italic("T. bidentata")))) +
  theme(plot.title = element_text(vjust = 1),
        panel.border = element_rect(color="black", size=2.3),
        legend.position = "none") +
  xlab("") -> tbiden.2021 
```

```{r plot summer 2022}
metadata %>% 
  # get column names/values nice for plotting
  mutate(Nutrients = case_when(nutrients == "Y" ~ "Enriched",
                               nutrients == "N" ~ "Ambient")) %>% 
  mutate(Crab = case_when(crab == "Y" ~ "Crab",
                               crab == "N" ~ "No crab")) %>% 
  # only looking at corals in the crab treatment
  filter(Crab == "Crab") %>% 
  ggplot(aes(x = Nutrients, y = tbiden_13_month, fill = Nutrients)) +
  geom_boxplot(size = 1,
               outlier.shape = NA) +
  geom_point(size = 2.2,
             color = "black",
             alpha = 0.65,
             position = position_jitterdodge(jitter.width = 0.2,
                                             jitter.height = 0,
                                             dodge.width = 0.75)) +
  scale_fill_manual(values = c("Enriched" = n.color,
                               "Ambient" = b.color)) +
  ylab(expression(paste("Large ", italic("T. bidentata")))) +
  theme(plot.title = element_text(vjust = 1),
        panel.border = element_rect(color="black", size=2.3),
        legend.position = "none") +
  xlab("") -> tbiden.2022
```

```{r plot together}
pdf(here("figures", "tbiden_abundance.pdf"), height = 5, width = 12)

tbiden.2021 + tbiden.2022 + plot_annotation(tag_levels = c('a'), tag_prefix = '(',
                            tag_suffix = ')')


dev.off()
```

# Model

Make this model for just the corals that started with a crab

```{r get just crab retention}
metadata %>% 
  filter(crab == "Y") -> crab_abundances
```

First try Poisson

```{r poisson model}
m.crab.1 <- glmmTMB(tbiden_13_month ~ nutrients + scale(coral_vol_cm3) + (1|block),
                       family = poisson(link = "log"),
                       data = crab_abundances
                       )
```

```{r test assumptions}
# get residuals
resid.crab.1 <- DHARMa::simulateResiduals(m.crab.1)

testResiduals(resid.crab.1, plot = T)
testDispersion(resid.crab.1)
testZeroInflation(resid.crab.1)
testQuantiles(resid.crab.1, plot = T)
check_model(m.crab.1)
```

No interaction so use type II ANOVA

```{r examine results}
car::Anova(m.crab.1, type = 2)
```

# Crab abundance stats

```{r}
# percent of crabs that were lost in the first summer of the experiment
1 - sum(crab_abundances$tbiden_1_month)/40

# number of crabs that were present on nutrient corals at the end of 13 months
sum(crab_abundances[crab_abundances$nutrients == "Y",]$tbiden_13_month)

# number of crabs that were present on ambient corals at the end of 13 months
sum(crab_abundances[crab_abundances$nutrients == "N",]$tbiden_13_month)
```




